### ISSUE TITLE
how to disable configuring a pool?

### ISSUE THREAD

**Issue by rduffner** [trombik/ansible-role-ntpd#5]
##### ISSUE TYPE

 - Bug Report

##### ROLE VERSION

```
1.4.0
```

##### OS / ENVIRONMENT

macOS HS 10.13.4 managing FreeBSD 11.1-RELEASE-p9

##### SUMMARY

It seems, a pool is configured even though I don't want this.
I only have one upstream (or two) and all have fixed IPs.

##### STEPS TO REPRODUCE

see the example in the readme

```yaml

```

```
```

##### ACTUAL RESULTS

I still get the line
pool 0.pool.ntp.org iburst

in the ntp.conf

I have my own stratum 1 devices, I don't need the pool.

**Comment by trombik** [comment]
please try [simplify_template](https://github.com/trombik/ansible-role-ntpd/tree/simplify_template) branch. it removes hard-coded logic. see also [backward-incompatibilities](https://github.com/trombik/ansible-role-ntpd/blob/simplify_template/CHANGELOG.md#release-xyz).
